name: mtw_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  device_preview: ^0.7.4
  sizer: ^2.0.13
  flutter_svg: ^0.22.0
  flutter_typeahead: ^3.2.0
  http: ^0.13.3
  faker: ^2.0.0
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  toggle_switch: ^1.2.0
  fluttertoast: ^8.0.8
  decimal: ^1.3.0
  shared_preferences: ^2.0.7
  flutter_phoenix: ^1.0.0
  restart_app: ^1.1.0
  flutter_slidable: ^0.6.0
  date_count_down: ^1.0.2
  flutter_countdown_timer: ^4.1.0
  google_fonts: ^2.1.0
  url_launcher: ^6.0.10
  youtube_player_flutter: ^8.0.0
  percent_indicator: ^3.4.0
  social_share: ^2.1.1
  flutter_icons: ^1.0.0+1
  flutter_rating_bar: ^4.0.0
  camera: ^0.9.2+2
  dio: ^4.0.4
  syncfusion_flutter_barcodes: ^19.3.56
  flutter_phone_direct_caller: ^2.1.0
  flutter_barcode_scanner: ^2.0.0
  sign_in_with_apple: ^3.3.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  image_path: "assets/images/logofti77.jpg"
  android: true
  ios: true
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Bold.ttf
  #         style: Bold
  #         weight: 900

    # fonts:
    # - family: Kanit
    #   fonts:
    #     -  asset: fonts/Kanit-Regular.ttf
    #     -  asset: fonts/Kanit-Italic.ttf
    #        style: italic
    #     -  asset: fonts/Kanit-Bold.ttf
    #        weight: 700